version: '3'

services:
    web:
        image: nginx
        container_name: "${APP_SLUG}-web"
        volumes:
            - ./.docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
            - .:/var/www/html
        ports:
            - '8080:80'
        restart: always
        depends_on:
            - php
            - db

    php:
        build:
            context: ./.docker/php/
        container_name: "${APP_SLUG}-php"
        restart: always
        volumes:
            - .:/var/www/html

    db:
        image: mysql:8.2
        container_name: "${APP_SLUG}-db"
        ports:
            - '3306:3306'
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        volumes:
            - ~/.docker/data/${APP_SLUG}/db:/var/lib/mysql

    redis-primary:
        image: redis:latest
        container_name: '${APP_SLUG}-redis-primary'
        command: redis-server --requirepass ${REDIS_PASSWORD}
        volumes:
            - ./.docker/redis/redis.conf:/etc/redis/redis.conf
            - ${REDIS_DATA_PATH}:/var/lib/redis
        networks:
            - redis-replication
        ports:
            - '${REDIS_PORT}:6379'

    redis-slave:
        image: redis:latest
        container_name: '${APP_SLUG}-redis-replica'
        ports:
            - '${REDIS_REPLICA_PORT}:6379'
        command: redis-server --requirepass ${REDIS_PASSWORD} --masterauth ${REDIS_PASSWORD} --replicaof ${APP_SLUG}-redis-primary ${REDIS_PORT}
        depends_on:
            - redis-primary
        volumes:
            - ./.docker/redis/replica/redis.conf:/etc/redis/redis.conf
        networks:
            - redis-replication

    composer:
        image: composer
        container_name: "${APP_SLUG}-composer"
        volumes:
            - .:/var/www/html
        command: composer install
        working_dir: /var/www/html
        depends_on:
            - php

    artisan:
        build:
            context: ./.docker/php/
        container_name: "${APP_SLUG}-artisan"
        volumes:
            - .:/var/www/html
        depends_on:
            - db
        working_dir: /var/www/html
        entrypoint: ['/var/www/html/artisan']

networks:
    redis-replication:
        driver: bridge
